[package]
name = "multithreading"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
rayon = "1.10.0"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "multi_thread_bench"
harness = false